promostandards:
  pcna:
    id: UNDERABUCK
    password: TBD
    product_sellable:
      wsdl: https://psproductdata100-stg.pcna.online/psProductData.svc?singleWsdl
      version: 1.0.0
      function: get_product_sellable
    product:
      wsdl: https://psproductdata100-stg.pcna.online/psProductData.svc?singleWsdl
      version: 1.0.0
      function: get_product
    product_pricing:
      wsdl: 'https://pspriceconfig100-stg.pcna.online/psPriceConfig.svc?singleWsdl'
      version: 1.0.0
      function: get_available_charges

