promostandards:
  pcna:
    product_sellable:
      endpoint: https://psproductdata100-stg.pcna.online
    product:
      endpoint: https://psproductdata100-stg.pcna.online
    available_charges:
      endpoint: https://pspriceconfig100-stg.pcna.online
    fob_points:
      endpoint: https://pspriceconfig100-stg.pcna.online
    configuration_and_pricing:
      endpoint: https://pspriceconfig100-stg.pcna.online
