promostandards:
  pcna:
    id: UNDERABUCK
    code: pcna
    name: pcna
    password: TBD
    endpoint: 
    product_sellable:
      endpoint: TBD
      wsdl: 'psProductData.svc?singleWsdl'
      version: 1.0.0
      function: get_product_sellable
    product:
      endpoint: TBD
      wsdl: psProductData.svc?singleWsdl
      version: 1.0.0
      function: :get_product
    available_charges:
      endpiont: TBD
      wsdl: 'psPriceConfig.svc?singleWsdl'
      version: 1.0.0
      function: get_available_charges
    fob_points:
      endpiont: TBD
      wsdl: 'psPriceConfig.svc?singleWsdl'
      version: 1.0.0
      function: get_fob_points
    configuration_and_pricing:
      endpiont: TBD
      wsdl: 'psPriceConfig.svc?singleWsdl'
      version: 1.0.0
      function: get_configuration_and_pricing